### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by amery78** [timothyl13241/Invoxia-HA#11]
First, thank you for this really cool integration !
Works like a charm ;)
Do you think it could be feasible to manage alert messages from the invoxia ?
Would like to be able to trigger an alerte when the sensor is moved (invoxia app send you an alerte if sensor detect movement, useful to detect theft attempts on a bike).

Kr,

Axel

**Comment by MagnusErler** [comment]
Does this work for you?

```
alias: Notify on Movement
description: ""
triggers:
  - entity_id:
      - device_tracker.tracker_0e6ede
    attribute: latitude
    trigger: state
  - entity_id:
      - device_tracker.tracker_0e6ede
    attribute: longitude
    trigger: state
actions:
  - data:
      message: Your device has moved to a new location!
    action: notify.notify
mode: single
```
